### ISSUE TITLE
缺少jinja 模块

### ISSUE THREAD

**Issue by jiaxiaolei** [bukun/TorCMS#2]
你好，我试用了一下。 使用 requirements.txt 安装之后，提示 jinja2 缺失。

requirements.txt 中缺少 jinja2 模块
Jinja2==2.8

**Comment by bukun** [comment]
已经添加了，多谢提醒。
另外要注意，现在的主题，使用的是Tornado的功能进行HTML渲染。 Jinja2只是做的接口，并未实际用到。
