### ISSUE TITLE
tpl静态文件是不是漏提交了？

### ISSUE THREAD

**Issue by xidianwlc** [bukun/TorCMS#3]
tpl静态文件是不是漏提交了？

**Comment by bukun** [comment]
这个不是漏掉了。原来的时候自带 Demo ， 可以直接使用。 后来在进行合并的时候，只保留了 Python 核心代码，没再合并 Demo ，把Demo去掉了。 现在可以使用 Maplet 这个。 Maplet算是应用， 由TorCMS提供核心功能。
