### ISSUE TITLE
网站后台从哪里进

### ISSUE THREAD

**Issue by riddle911** [bukun/TorCMS#4]
大神，网站已经跑起来了。但是....恕我蠢，没找到后台在哪里。
还望告知一二。

**Comment by bukun** [comment]
抱歉，这个没写清楚。
访问url为：    /admin/ 。

另外，目前后台不太完善。后台是后加的，开始是没有后台的。

**Comment by riddle911** [comment]
哦~看到了。老哥您没有做后台之前 网站是怎么维护的- -
我是想看看做个个人小站试试。

**Comment by bukun** [comment]
内容添加在用户面板中有。在登陆的情况下，打开页面，有编辑链接。
